### ISSUE TITLE
Adding existing fixtures to the leaderboards and setting auto update leaderboard on Fixture creation.

### ISSUE THREAD

**Issue by rpc404** [rpc404/playpoint-pusher#97]
**Is your feature request related to a problem? Please describe.**
In the prediction page, the leaderboards must contain all active fixtures of the same Marketplace. The leaderboard Items must be sorted as the highest sum of Users & Volume of the fixture.
```
Say, Qatar/Ecuador has 10 predictions 
i.e. user = 10
total prediction amount is calculated by looping all the predictions. 
Say, volume += predictionAmount.
predictionAmount(volume) = 100
thus, sum = user + volume = 110.

The other 2 fixtures have the sum of 140 and 90,
Then, the leaderboard must be sorted as [90,110,140]
```

**Describe the solution you'd like**
On this controller of `Fixture.js` on res.status = 200. `createLeaderboard` must be called from `Leaderboard.js`.
```
newFixtureController: expressAsyncHandler(async (req, res) => {
    res.status(200).json({
      ...
    });
  }),
```

The format for the new leaderboard is 
```
{
    "marketplaceSlug": "",
    "fixture": {
        "fixtureId": "6379ea2e273e07297e490cf0",
        "HomeTeam": "",
        "AwayTeam": ""
    },
    "totalUsers": 0,
    "totalVolume": 0,
    "created_at": "2022-11-26T16:41:42.701Z"
}
```

**Describe alternatives you've considered**
For the alternative for the fixture to be listed.
Algorithm:
1. Get All Predictions using Axios or mongoose.
2. Get All Fixtures using Axios or mongoose.
3. From the fixture object use HomeTeam and AwayTeam names and use volume from predictions
4. Total user count is total predictions.
5. Delete the controller after all the fixtures are added to the leaderboards.

**Additional context**
Use the following link for the format of REST API requests.
[API Documentation](https://documenter.getpostman.com/view/24395787/2s8YmHwjTu#99daa6ee-f681-4cdc-9e03-792b7421d7f0)

**Comment by SudeepMi** [comment]
Leaderboards are generated dynamically and cached in backend itself without storing in database
